### ISSUE TITLE
getting MalformedJsonException

### ISSUE THREAD

**Issue by rafaelcamargossantos** [vimeo/vimeo-networking-java#105]
I'm integrating the sdk in my android aplication using a fixed acess token (generated through the website).

This is my code to initialize the vimeoclient

`Configuration.Builder configBuilder;

    public void initVimeo(){
        configBuilder = getAccessTokenBuilder();
        VimeoClient.initialize(configBuilder.build());

    }

    public Configuration.Builder getAccessTokenBuilder() {
        // The values file is left out of git, so you'll have to provide your own access token
        String accessToken = Constants.VIMEO_ACESS_TOKEN;
        return new Configuration.Builder(accessToken);
    }`

This is how I'm fetching the video:

`String url = "https://vimeo.com/106381957";

        VimeoClient.getInstance().fetchContent(url, CacheControl.FORCE_NETWORK, new ModelCallback<Video>(Video.class) {
            @Override
            public void success(Video video) {
                if (video != null) {
                    Log.d("VIMEO RESULT: ", video.embed.html);

                    //Auto playing vimeo videos in Android webview
                    mWebView.getSettings().setJavaScriptEnabled(true);
                    mWebView.getSettings().setAllowFileAccess(true);
                    mWebView.getSettings().setAppCacheEnabled(true);
                    mWebView.getSettings().setDomStorageEnabled(true);
                    mWebView.getSettings().setPluginState(PluginState.OFF);
                    mWebView.getSettings().setAllowFileAccess(true);

                    String mime = "text/html";
                    String encoding = "utf-8";
                    mWebView.loadDataWithBaseURL(null, video.embed.html, mime, encoding, null);

                    setContentView(mWebView.getLayout());

                    //Esconder a Status Bar
                    View decorView = getWindow().getDecorView();
                    // Hide the status bar.
                    int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN;
                    decorView.setSystemUiVisibility(uiOptions);
                    // Remember that you should never show the action bar if the
                    // status bar is hidden, so hide that too if necessary.
                    ActionBar actionBar = getActionBar();
                    if(actionBar!=null) {
                        actionBar.hide();
                    }

                }
            }

            @Override
            public void failure(VimeoError error) {
                String errorMessage = error.getDeveloperMessage();
                Log.d("VIMEO RESULT: ", errorMessage);
            }
        });`

However I'm getting a error response as follows:

Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

**Comment by kevinzetterstrom** [comment]
Hi Rafael,

You mentioned your url is ```https://vimeo.com/106381957```, however, the ```fetchContent``` method you are using does not take a url, it takes a uri. This library takes care of forming the url; you will end up actually hitting ```https://api.vimeo.com```, not ```https://vimeo.com```. The uri format to get a video for the id mentioned is ```/videos/106381957```, however, we would not recommend constructing this yourself and instead relying on this API to obtain the uri.

If you have a ```Video``` object, such as ```someVideo```, your request will look like this:
```
VimeoClient.getInstance().fetchContent(someVideo.uri, CacheControl.FORCE_NETWORK, 
    new ModelCallback<Video>(Video.class) {...});
```

To get a ```Video``` object, or a rather a list of them in a ```VideoList``` object, for which you own, you would make a similar ```fetchContent``` request with the uri ```/me/videos``` like

```
VimeoClient.getInstance().fetchContent("/me/videos", CacheControl.FORCE_NETWORK, 
    new ModelCallback<VideoList>(VideoList.class) {...});
```

**Comment by rafaelcamargossantos** [comment]
Got it working here with this changes!

Thank you for the fast answer @kevinzetterstrom !

**Comment by manyakprogramci** [comment]
> Hi Rafael,
> 
> You mentioned your url is `https://vimeo.com/106381957`, however, the `fetchContent` method you are using does not take a url, it takes a uri. This library takes care of forming the url; you will end up actually hitting `https://api.vimeo.com`, not `https://vimeo.com`. The uri format to get a video for the id mentioned is `/videos/106381957`, however, we would not recommend constructing this yourself and instead relying on this API to obtain the uri.
> 
> If you have a `Video` object, such as `someVideo`, your request will look like this:
> 
> ```
> VimeoClient.getInstance().fetchContent(someVideo.uri, CacheControl.FORCE_NETWORK, 
>     new ModelCallback<Video>(Video.class) {...});
> ```
> 
> To get a `Video` object, or a rather a list of them in a `VideoList` object, for which you own, you would make a similar `fetchContent` request with the uri `/me/videos` like
> 
> ```
> VimeoClient.getInstance().fetchContent("/me/videos", CacheControl.FORCE_NETWORK, 
>     new ModelCallback<VideoList>(VideoList.class) {...});
> ```

Thanks bro.
