### ISSUE TITLE
ported to retrofit2 2.1.0 and support annotations...want me to upload?

### ISSUE THREAD

**Issue by philippela** [vimeo/vimeo-networking-java#115]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by kevinzetterstrom** [comment]
1.1.0 of this library will support Retrofit 2.x rather than Retrofit 2 beta.
What annotations are you supporting?

**Comment by philippela** [comment]
1.1.0 is already out and it's not at retrofit2 2.1.0
android.support.annotation

**Comment by kevinzetterstrom** [comment]
This library has no dependencies on Android at the moment, and we would like to keep it that way. 1.1.0 is not "out" yet. You could build it as a submodule which would fail, at the moment, for you since a dependency stag-java is not yet open sourced and is a private repo.

**Comment by philippela** [comment]
OK for annotations
I took in the master branch and worked from there

**Comment by kevinzetterstrom** [comment]
Sorry for the delay responding to this, and thanks for taking the time to work on it. However, we will be updating the library soon, so we can update the dependencies at that time.
