### ISSUE TITLE
playback issue on S4

### ISSUE THREAD

**Issue by philippela** [vimeo/vimeo-networking-java#145]
#### Issue Summary
The video does not render correctly on the S4, only towards the end

it's ok with the vimeo app

So what's the trick?

**Comment by kevinzetterstrom** [comment]
Hi @philippela , this library is about data consumption, not video playback. Can you open a question on StackOverflow instead? With your question, it would be helpful to know exactly how you are trying to play videos - are you using a WebView? a VideoView? A library such as ExoPlayer? Do you experience issues on other devices, or just the S4? Are you a Pro member trying to play your own videos?

Also, please share your relevant player code when posting, it will allow helping you that much easier. Be sure to tag ```vimeo-android``` so we can be alerted to your post - looking forward to helping!
