### ISSUE TITLE
How to upload video to Vimeo from Android app using this Library?

### ISSUE THREAD

**Issue by coneits** [vimeo/vimeo-networking-java#146]
Hello.

I would like to upload video to vimeo from my android app.
Can I upload video from my android app using your github repository?
Or is there any other published github source code that can upload video?

Thanks,
Look forward to hearing from you.

Best Regards.

**Comment by kevinzetterstrom** [comment]
@coneits 
Right now this library does not provide assistance with the upload flow.
Please see my answer to this same question [here](https://github.com/vimeo/vimeo-deeplink-android/issues/17).
Closing this so we can keep the dialog open in one ticket.
