### ISSUE TITLE
How to Download Video for Pro Account?

### ISSUE THREAD

**Issue by naveenkumarmallappa** [vimeo/vimeo-networking-java#162]
#### Issue Summary
Is there any chance to download Video form Pro Account?

**Comment by kvenn** [comment]
Can you clarify? If the video is your own (and you have a pro account), you have access to the `files` field on the `Video` object. The `VideoFile` object which is contained in the `files` array will hold several versions of your video: HLS, DASH, progressive, etc. The progressive video is usually an `mp4` which you can download (it'll be of quality type `HD` or `SD`).

This library will give you access to getting the `Video` object, but once you have it, you'll have to download the `.mp4` resource yourself (there are several libraries capable of doing this).

If the video does not belong to you or you do not have a pro account, you will not be able to access the `files` array.

**Comment by kevinzetterstrom** [comment]
@naveenkumarmallappa do you have any issues on the above? If not, I will close this issue out.

**Comment by naveenkumarmallappa** [comment]
No issues @kevinzetterstrom. You can marked it as closed. 
Thank you
