### ISSUE TITLE
VideoFile is empty, #Pro account

### ISSUE THREAD

**Issue by 3abdrabou** [vimeo/vimeo-networking-java#179]
#### Issue Summary
I have a pro account, and i can not access to the files field on the Video object, the ArrayList<VideoFile> is empty.

**Comment by kevinzetterstrom** [comment]
Hi @3abdrabou can you confirm that the `Video` object is one that you own? That is, a `Video` that the user who is represented by the auth token you are using owns?

**Comment by 3abdrabou** [comment]
@kevinzetterstrom , thank you for your response, i have manually uploaded the video in Vimeo account, and i want to access it in android app. is that i can not access other videos uploaded by other user in same vimeo account ?

**Comment by kevinzetterstrom** [comment]
Can you supply the access token you are using, along with the video uri in question? I will run a quick test.

**Comment by 3abdrabou** [comment]
Yes, here is the code : `22954cb57b95a029c24349a49082021c`

**Comment by 3abdrabou** [comment]
Dear @kevinzetterstrom , it's work!, i forgot to pass the access token in `Configuration.Builder`
thank you!

**Comment by kevinzetterstrom** [comment]
Glad to see you got it working! I'll close this issue now.
