### ISSUE TITLE
Vimeo-Networking.jar file 

### ISSUE THREAD

**Issue by Cortlandd** [vimeo/vimeo-networking-java#194]
#### Issue Summary
Is there a, or a plan for a jar file to be able to use the library?

#### Reproduction Steps
Detailed steps to reproduce the issue.
N/A
#### Expected Behavior
N/A
#### Actual Behavior
N/A

**Comment by kevinzetterstrom** [comment]
To clarify, are you asking if we intend to supply versioned jar files within this repository to download as an alternative to it being hosted on Bintray and jCenter?

**Comment by Cortlandd** [comment]
Yes. My apologies about that. 😅

**Comment by kevinzetterstrom** [comment]
We don't have any plans to host the jar files within this repo. However, you can access them via Bintray [here](https://bintray.com/vimeo/maven/vimeo-networking/1.1.0#files) and download them just like you would if we were to host them.

**Comment by kevinzetterstrom** [comment]
@Cortlandd I just wanted to follow up on this. Do you have any questions with the above? If not, I will close this issue out.

**Comment by kevinzetterstrom** [comment]
Closing this issue as resolved, if you have another issue, please feel free to open another.

**Comment by Cortlandd** [comment]
Shit, sorry about that. But yes my issue was resolved.
