### ISSUE TITLE
How to play a private video?

### ISSUE THREAD

**Issue by devsideal** [vimeo/vimeo-networking-java#222]
#### Issue Summary
I want to upload videos on vimeo, that should be play only from my android app,  using this library

#### Reproduction Steps
To achieve this:
1. I uploaded private video (uploaded with the privacy option 'Only I can see this video' ) on vimeo.
2. After configuration call the method fetchMyVideo("xxxxxxx");
```
private void fetchMyVideo(String id) {
VimeoClient.getInstance().fetchNetworkContent("/videos/"+id, new ModelCallback<Video>(Video.class) {
     @Override
     public void success(Video video) {
          String html = video.mEmbed != null ? video.mEmbed.getHtml() : null;
          // VimeoActivity.class have a webview to load this html
          Intent mIntent = new Intent(this, VimeoActivity.class);
          mIntent.putExtra("html", html);
          startActivity(mIntent);
     }
     @Override
     public void failure(VimeoError error) {
     }
});
}
```
4. But WebView showing message "Private video, Login to watch...." ?

#### Expected Behavior
Private video should play using this library with provided access token.

#### Actual Behavior
Video is not playing and  WebView showing message "Private video, Login to watch..." ?

**Comment by kevinzetterstrom** [comment]
Hi @devsideal,

Android WebViews are not a part of this library; the WebView you are attempting to use to play a video is a part of your application. The behavior you are experiencing is the same as if you opened that private video in any web browser - you would be forced to login to your account before accessing it. Essentially, you are attempting something that this library does not support.

As an alternative approach, if you have a Vimeo PRO account and authenticate with the `video_files` scope, you will have access to the raw video files. In the `success` block above where you access the `Video`, you could grab these video files and play them natively within the application. Android MediaPlayer and ExoPlayer are both capable of playing video files. This library does not provide a way for you to play these videos through this method either - this is just a suggestion of how you _could_ accomplish playing private videos within your application.

**Comment by devsideal** [comment]
I don't want to use any other player except vimeo player due to bandwidth, 
any other way to play private video using vimeo player within my app?

**Comment by kevinzetterstrom** [comment]
@devsideal please see my previous response on an alternate solution.

**Comment by devsideal** [comment]
Yes, I saw but i don't want force to user for login to watch videos, are there any way to login from background and see the videos?

**Comment by kevinzetterstrom** [comment]
Well, you need to be authenticated to use this library - all requests will fail without some kind of authorization.  I've taken you have already successfully been able to do this since you have been able to make the above request to obtain a `Video`.
What you want to accomplish could be done by authenticating as you (the uploader). Consumers of your application wouldn't need to log in themselves.

**Comment by kevinzetterstrom** [comment]
@devsideal do you have any more questions around this issue? If not, I will close this.

**Comment by kevinzetterstrom** [comment]
Closing this issue as resolved, if you have another issue, please feel free to open another.

**Comment by ishtiaqn2o** [comment]
Hello, I am trying to play video using native player.. but i am getting mPlay= null into video object.

also  
mApiClient.fetchNetworkContent("/videos/"+id, new ModelCallback<Video>(Video.class) {
            @Override
            public void success(Video video) {
               
            }
            @Override
            public void failure(VimeoError error) {
            }
        });

fetchNetworkContent cannot resolve..
