### ISSUE TITLE
ssl: CertPath ValidatorException

### ISSUE THREAD

**Issue by amank22** [vimeo/vimeo-networking-java#241]
#### Issue Summary
When playing some videos on some devices, it shows CertPath ValidatorException.
Trust anchor not found.

#### Expected Behavior
Should play videos normally as it is working on many devices but giving ssl exception on some devices.

#### Actual Behavior
SSL error.

You can give an option for customizing the okhttp client used in library.

**Comment by kevinzetterstrom** [comment]
Hi @amank22 
Thanks for submitting an issue, and I would just like to clarify something. You specifically say there is a cert issue when playing videos, but this library does not play videos. Do you mean when requesting videos?

Would you be able to provide some sample code on how you are using this library and the stack trace? What devices are throwing exceptions? We would love to help you troubleshoot this, but we will need more information to do so.

**Comment by amank22** [comment]
Sorry it is while fetching video file from vimeo sdk.
![screenshot_2017-08-03-20-16-51](https://user-images.githubusercontent.com/3993720/29170548-c0d573e8-7df6-11e7-9d24-6abd7dc5119a.png)

I have added the screenshot. I don't the full stacktrace as this is happening to some random users.
Will reply with device as soon as I get it.

**Comment by kevinzetterstrom** [comment]
Great thanks. By default, a `Configuration` is created with certificate pinning on. You can create it with it turned off, by using `enableCertPinning(false)` on the Configuration Builder. Additionally, once you have a `Configuration`, you could call `setCertPinningEnabled(false)`, then, pass this Configuration to `VimeoClient#initialize(Configuration)`. Can you try this and let me know if it solves your problem?

**Comment by amank22** [comment]
I have already tried with enableCertPinning(false) still unable to get the video file. 
From what I could find on other sources related to this is about some ssl certificate problem maybe from the server.
Will adding some certificate in app can make any difference?? Even for that the okhttp client needs to be exposed from the library to make it configurable according to user need.

**Comment by kevinzetterstrom** [comment]
Can you provide us with the code you are using? Specifically, we would like to see your setup code and the code making the request. Also, is this a specific video, or is it happening to several? Please provide uris for the videos that are problematic. We would like to try and reproduce your issue as a next step.

**Comment by amank22** [comment]
> Initializing with this

`Configuration.Builder vimeoConfigurationBuilder = getVimeoConfigurationBuilder(accessToken);
        VimeoClient.initialize(vimeoConfigurationBuilder.build());`

> Fetching Video File

`
public static void fetchVimeoVideo(Uri uri, ModelCallback<Video> modelCallback) {
        String id = uri.getLastPathSegment();
        String url = "/videos/" + id;// the video uri; if you have a Video, this is video.uri
        VimeoClient.getInstance().fetchNetworkContent(url, modelCallback);

    }

    private void fetchVimeoVideo(final Uri uri) {
        final ModelCallback<Video> videoModelCallback = new ModelCallback<Video>(Video.class) {
            @Override
            public void success(Video video) {
                // use the video
                if (video == null) {
                    failToFetchVimeoVideoRetry(uri);
                    return;
                }
                Play play = video.getPlay();
                if (play != null) {
                    VideoFile hlsVideo = play.getHlsVideoFile();
                    if (hlsVideo != null) {
                        playVimeoVideo(hlsVideo.getLink(), true);
                    } else {
                        //Show popup error
                    }
                } else {
                    ArrayList<VideoFile> videoFiles = video.files;
                    if (videoFiles != null && !videoFiles.isEmpty()) {
                        VideoFile videoFileSmall = videoFiles.get(0);
                        for (VideoFile videoFile : videoFiles) {
                            if (videoFile.getQuality().equals(VideoFile.VideoQuality.HLS)) {
                                videoFileSmall = videoFile;
                                break;
                            }
                            if ((videoFile.getWidth() / videoFileSmall.getHeight()) < (videoFileSmall.getWidth() / videoFileSmall.getHeight())) {
                                videoFileSmall = videoFile;
                            }
                        }
                        // you could sort these files by size, fps, width/height
                        String link = videoFileSmall.getLink();

                        if (videoFileSmall.getQuality().equals(VideoFile.VideoQuality.HLS)) {
                            playVimeoVideo(link, true);
                        } else {
                            playVimeoVideo(link, false);
                        }
                    } else {
                        //Show popup error
                    }
                }
            }

            @Override
            public void failure(VimeoError error) {
                // voice the error, show some error and show retry popup
                failToFetchVimeoVideoRetry(uri);
            }
        };
        VimeoHelper.fetchVimeoVideo(uri, videoModelCallback);
    }`

**Comment by amank22** [comment]
Can't get the video uri but will comment as soon as I get it from user.

**Comment by kevinzetterstrom** [comment]
@amank22 any update on this?

**Comment by amank22** [comment]
@kevinzetterstrom Hey. Unfortunately, I couldn't find the url. Well, for now, we have shown an embedded video. You may close this issue for not having enough data. 
Anyway thanks for helping. :)

**Comment by mayank250004** [comment]
Facing same problem.

Any solution ?
