### ISSUE TITLE
Is this is a webview player or native player?

### ISSUE THREAD

**Issue by WTASTUDIOSINDIA** [vimeo/vimeo-networking-java#272]
#### Issue Summary
I want to play vimeo videos on android application. What are the steps to do that? Client asking me do not integrate with webview. Please help me in this.

**Comment by anthonycr** [comment]
Currently, the only way to play vimeo videos in your application is through the WebView using the `Video.Embed` object. You can use `video.getEmbed().getHtml()` to get the HTML to load into the WebView.
