### ISSUE TITLE
Can you not use the Retrofit library?

### ISSUE THREAD

**Issue by jclova** [vimeo/vimeo-networking-java#276]
Correct me if I am wrong.
If I include this library, then I have to use the Retrofit library version that you are using.
I know you guys are keep updating your library to use the latest Retrofit library version. However, until you release a new build, I am stuck with the older version of the Retrofit library.

Our company makes libraries(SDK) for our clients and if we include your library to our library(SDK), then our clients are stuck with the Retrofit version which you are using too.

Whenever the Retrofit library upgrade is 100% backwards compatible with the older version, then I could replace with the newer version. However, it is not the case all the time, right?

**Comment by howardrigberg** [comment]
You should be able to use gradle to `exclude` our Retrofit version and use yours. In theory this should work. Give it a try and let us know if you don't have success with that approach.

**Comment by jclova** [comment]
I could be wrong.
Between the versions, if the new version is 100% backwards compatible, then it could work.
However, let's say:

**Version 1.0.0**
Retrofit.hello();

**Version 1.1.0**
Retrofit.hello(); <- Removed

If your library uses the Retrofit version 1.0.0 and calls **Retrofit.hello();**, then by excluding Retrofit library 1.0.0 and loading version 1.1.0 will crash.

**Comment by msya** [comment]
@jclova Closing out this issue as the library should not cause any backwards compatibility issues. However, if you encounter any problems, please let us know!
