### ISSUE TITLE
Android vimeo intergration AssertionError("Instance must be configured before use")  i got these error

### ISSUE THREAD

**Issue by Jayapriya25** [vimeo/vimeo-networking-java#283]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by msya** [comment]
Hey @Jayapriya25 Thanks for opening an issue. This exception occurs, because `VimeoClient#getInstance` was called before initializing `VimeoClient`. To verify, are you creating a `Configuration` object through the builder and initializing `VimeoClient`?

For example:

```
Configuration.Builder configBuilder =
      new Configuration.Builder(clientId, 
                                                  clientSecret, 
                                                  SCOPE, 
                                                  testAccountStore)
          .setCacheDirectory(this.getCacheDir());
VimeoClient.initialize(configBuilder.build());
```
