### ISSUE TITLE
class path not found intergratrating vimeo

### ISSUE THREAD

**Issue by Jayapriya25** [vimeo/vimeo-networking-java#284]
#### Issue Summary
:"Warning:[options] bootstrap class path not set in conjunction with -source 1.7"e.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by howardrigberg** [comment]
@Jayapriya25 Can you please provide some more details about your reproduction steps and how you are integrating the library? Thanks!

**Comment by kvenn** [comment]
It sounds like this might either be something incorrectly set up in your environment (either IDE or OS). I found a post from someone with a similar issue [here](http://insidejvmjava.blogspot.com/2015/09/ant-compile-issue-warning-options.html).

> During the ant build I was facing this issue.
> It caused because I had two JDK in my system, 1.6 and 1.7.
> I used 1.6 in eclipse as JRE during coding but I was using cmd line for ant build.
> In the command line java -version displaying JAVA_HOME as 1.7.
> Solution:
> Just change the JAVA_HOME via "System environment" in window or equivalent in other OS.
> Open New cmd promt.

You might have to additionally change the Java version you're using in Android Studio.
