### ISSUE TITLE
Upgrade com.intellij:annotations to avoid Dex Compiler D8 conflict issues

### ISSUE THREAD

**Issue by christianlacerda** [vimeo/vimeo-networking-java#285]
#### Issue Summary
The dependency **com.intellij**:annotations has been moved to a new group `org.jetbrains` as noticed [here](https://mvnrepository.com/artifact/com.intellij/annotations) but has kept the same package names for its classes. This is causing conflict with the new Dex Compiler (D8) and newer versions of libraries like `org.jetbrains.kotlin:kotlin-stdlib-jre7` which depends on the newer **org.jetbrains**:annotations.

#### Reproduction Steps
- With Android Studio 3.2 Canary 1, create a simple (Empty Activity) Android project with Kotlin support
- Add **app** dependency: `com.vimeo.networking:vimeo-networking:1.1.0`
- Run: `./gradlew assembleDebug`
#### Expected Behavior
No conflict issues.

#### Actual Behavior
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: org.intellij.lang.annotations.JdkConstants$PatternFlags

#### Workaround
Exclude vimeo-networking dependency on `com.intellij:annotations`
```
implementation("com.vimeo.networking:vimeo-networking:$vimeoNetworkingVersion", {
        exclude group: "com.intellij", module: "annotations"
    })
```

**Comment by msya** [comment]
Closing this issue as it has been fixed in version 1.1.3 in the PR #321. Please let us know if you see this problem again.
