### ISSUE TITLE
get build error after I includ this module to my project

### ISSUE THREAD

**Issue by ives9999** [vimeo/vimeo-networking-java#289]
Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [/Users/ives/android/bm/app/build/intermediates/multi-dex/debug/componentClasses.jar] (Can't read [/Applications/Android Studio.app/Contents/gradle/m2repository/org/jetbrains/annotations/13.0/annotations-13.0.jar(;;;;;;**.class)] (Duplicate zip entry [annotations-13.0.jar:org/intellij/lang/annotations/Identifier.class]))

I get the error message, so I can't use this api.

my build.gradle(app) is as follow

`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    signingConfigs {
        config {
            keyAlias 'bm'
            keyPassword 'K5SD23r6'
            storeFile file('/Users/ivessun/android/bm/bm.jks')
            storePassword 'K5SD23r6'
        }
    }
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.sportpassword.bm"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation "com.android.support:appcompat-v7:$design_version"
    implementation "com.android.support:design:$design_version"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation "com.android.support:support-v4:$design_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.facebook.android:facebook-android-sdk:4.31.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile "com.android.support:appcompat-v7:$design_version"
    compile "com.android.support:design:$design_version"
    compile "com.android.support:recyclerview-v7:$design_version"
    compile "com.android.support:cardview-v7:$design_version"
    compile 'com.android.volley:volley:1.1.0'
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "org.jetbrains.anko:anko:$anko_version"
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile project(':vimeo-networking')
}
`

my build.gradle(bm)

`
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.21'
    ext.anko_version = '0.10.4'
    ext.design_version = '27.1.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven{url 'https://jitpack.io'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
can you resolve this problem?
Thanks.

**Comment by msya** [comment]
Closing this issue as it has been fixed in version 1.1.3 of the library in the PR #321. Please let us know if you encounter any further issues.
