### ISSUE TITLE
Picture#link_with_play_button does not exist

### ISSUE THREAD

**Issue by EdgeCaseBerg** [vimeo/vimeo-networking-java#296]
#### Issue Summary
In the [Picture](https://github.com/vimeo/vimeo-networking-java/blob/v1.1.0/vimeo-networking/src/main/java/com/vimeo/networking/model/Picture.java) class in v1.1.0 and [on the develop branch](https://github.com/vimeo/vimeo-networking-java/blob/develop/vimeo-networking/src/main/java/com/vimeo/networking/model/Picture.java) there is a `link` field / `getLink` method which corresponds to the link field in the API response. But in the API response there is also a `link_with_play_button` field:

<img width="296" alt="screen shot 2018-04-10 at 1 09 14 pm" src="https://user-images.githubusercontent.com/1691564/38572184-68a6c256-3cc0-11e8-8ca5-74ca07efaf8a.png">

It would be useful if this field was present in the `Picture` class so one could use it. (It would be especially useful if this was present in 1.1.x / 1.x.x versions)

#### Reproduction Steps
N/A

#### Expected Behavior
Expected ability to get `linkWithPlayButton` from `Picture` element

#### Actual Behavior
`linkWithPlayButton` field / getter does not exist

**Comment by msya** [comment]
@EdgeCaseBerg Thank you for opening an issue to add `link_with_play_button`. We added this field to the `Picture` class. It is now part of v1.1.2. Please check it out and lets us know if you have any issues. Thanks!

**Comment by EdgeCaseBerg** [comment]
@msya Thanks so much for doing this! I updated my dependency to point to the new version but got

```
[info] Resolving com.vimeo.networking#vimeo-networking;1.1.2 ...
[warn] 	module not found: com.vimeo.networking#vimeo-networking;1.1.2
[warn] ==== local: tried
[warn]   /.ivy2/local/com.vimeo.networking/vimeo-networking/1.1.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/vimeo/networking/vimeo-networking/1.1.2/vimeo-networking-1.1.2.pom
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/vimeo/networking/vimeo-networking/1.1.2/vimeo-networking-1.1.2.pom
```

Should I be pointing my build tool to a specific resolver to get this update?

**Comment by msya** [comment]
@EdgeCaseBerg Version 1.1.2 has been released to jcenter and maven central. Specifying jcenter or maven central as below should work. Please let me know if you have further issues.

```
    repositories {
        mavenCentral()
        jcenter()
    }
```

**Comment by EdgeCaseBerg** [comment]
@msya Thanks so much!

```
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo1.maven.org/maven2/com/vimeo/networking/vimeo-networking/1.1.2/vimeo-networking-1.1.2.jar ...
[info] 	[SUCCESSFUL ] com.vimeo.networking#vimeo-networking;1.1.2!vimeo-networking.jar (284ms)
```

Everything appears to be working now!
