### ISSUE TITLE
Difference between this lib and Vimeo Extractor

### ISSUE THREAD

**Issue by klaszlo8207** [vimeo/vimeo-networking-java#302]
https://github.com/ed-george/AndroidVimeoExtractor

What is the difference between this two libs?

**Comment by msya** [comment]
@klaszlo8207 This library contains more functionality. It is the official SDK that allows you interface with the Vimeo API in Java or Kotlin. In addition to getting videos, it contains features such as the ability to follow a user, category or create a channel.
