### ISSUE TITLE
How to get other user's private video?

### ISSUE THREAD

**Issue by naveenkumarmallappa** [vimeo/vimeo-networking-java#318]
#### Issue Summary
I am having pro account, and I am fetching my own video's but I need to fetch other user's private video's. How this is possible. If they shared accessToken with me is this possible? Or any otherway please provide.

#### Reproduction Steps
Is there any way to get other user's private video?

#### Expected Behavior
I have an user's video id which is his private video. And I am having pro account but I tried to fetch video object of other user is not able to fetch.  I am getting below error

> STATUS CODE: 404

But I can fetch my private video's successfully.
with following code.
```
String videoUri = "/videos/" + videoId;
        mApiClient.fetchNetworkContent(videoUri, new ModelCallback<Video>(Video.class) {
            @Override
            public void success(Video video) {
                videoName = video.name;
                Log.d("VideoName ::", video.name + " Te");
                playVideo(video);
            }

            @Override
            public void failure(VimeoError error) {
                Toast.makeText(MediaActivity.this, MediaActivity.this.getString(R.string.something_went_wrong), Toast.LENGTH_SHORT).show();
                Log.e("VimeoError : ", error.toString());
            }
        });
```

#### Actual Behavior
Can you provide any other way's to access other user video's. Is there access token is needed for that user to access vimeo network library.

**Comment by anthonycr** [comment]
There is no way to fetch a user's private videos if the current user does is not the owner the videos. If another user could access your private videos, then they would not be private. Private videos are meant to be visible only to the current user. 

The only way to get a user's private videos is to log in as that user, and, as you mentioned, use their access token to retrieve the user's videos.

**Comment by naveenkumarmallappa** [comment]
Thank you
