### ISSUE TITLE
hello pls help me..Actually i have pro account of vimeo and want to fetch mp3 path from vimeo android api,,,,,but i did not find getfiles options in vimo networking api

### ISSUE THREAD

**Issue by pawansharma1** [vimeo/vimeo-networking-java#322]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by MrTheGood** [comment]
hi I hev fix just get a video or video list then do video.files and ull hev `ArrayList<VideoFile>`. U can use `VideoFile.link` then

For your next question, please be bothered to write actual sentences.

**Comment by pawansharma1** [comment]
Actually when in fetch m play for fetch link of video ..it will remain always null...so what i do

**Comment by pawansharma1** [comment]
yes sir i will alresdy enabled it...

**Comment by pawansharma1** [comment]
sir pls help me what i do now

**Comment by MrTheGood** [comment]
Could you write a more detailed description of your problem and show what you've tried/done so far?

**Comment by pawansharma1** [comment]
Actually i want to play vimeo mp3 videos in my android app....i will done everything....but when i try to fetch  link of video it will show null........when i try to get video.getPlay().getProgressiveVideoFiles().get(0).getLink();

it will show null

**Comment by MrTheGood** [comment]
video.getPlay() is not supported yet, even though the documentation on the main branch uses it in the example. This is because the main branch is the development branch. 

Use https://github.com/vimeo/vimeo-networking-java/tree/master#native-playback as a reference. This shows the current way to do it. 

In short: 
```
Video video = ...; // obtain a video
ArrayList<VideoFile> videoFiles = video.files;
if(videoFiles != null && !videoFiles.isEmpty()) {
     VideoFile videoFile = videoFiles.get(0); // you could sort these files by size, fps, width/height
     String link = videoFile.getLink();
     // load link
}
```

**Comment by pawansharma1** [comment]
Video video = ...; what i do here.....

**Comment by MrTheGood** [comment]
Just get a video as you usually would, as shown [here](https://github.com/vimeo/vimeo-networking-java/tree/master#how-do-i-get-a-video-that-i-own)

**Comment by MrTheGood** [comment]
Just replace `video.getPlay().getProgressiveVideoFiles().get(0).getLink();` with `video.files.get(0).getLink()`

**Comment by pawansharma1** [comment]
videoTitlesString += video.files.get(0).getlink();


it will show error on.-    .files

**Comment by pawansharma1** [comment]
no file found by name of .files

**Comment by MrTheGood** [comment]
...What does the error say?

**Comment by pawansharma1** [comment]
![error](https://user-images.githubusercontent.com/15656807/43712172-f3e3f45e-9992-11e8-8dfa-8ac88b0cbfc7.png)

**Comment by MrTheGood** [comment]
What version of vimeo-networking-java are you using?

**Comment by pawansharma1** [comment]
i am using it from github

**Comment by pawansharma1** [comment]
[New folder (8).zip](https://github.com/vimeo/vimeo-networking-java/files/2262192/New.folder.8.zip)

**Comment by pawansharma1** [comment]
Any help pls

**Comment by MrTheGood** [comment]
Are you on the "master" branch?

**Comment by pawansharma1** [comment]
sorry no i am not on master branch....if u have any project on vimeo..pls share with me... i will make changes according to that

**Comment by MrTheGood** [comment]
I don't see why you would need that.. Just switch to the master branch (If you don't know how, I recommend you learn basic git commands)

**Comment by alexmazza** [comment]
> video.getPlay() is not supported yet, even though the documentation on the main branch uses it in the example. This is because the main branch is the development branch.
> 
> Use https://github.com/vimeo/vimeo-networking-java/tree/master#native-playback as a reference. This shows the current way to do it.
> 
> In short:
> 
> ```
> Video video = ...; // obtain a video
> ArrayList<VideoFile> videoFiles = video.files;
> if(videoFiles != null && !videoFiles.isEmpty()) {
>      VideoFile videoFile = videoFiles.get(0); // you could sort these files by size, fps, width/height
>      String link = videoFile.getLink();
>      // load link
> }
> ```
If I do this I get a link like this https://player.vimeo.com/external/26958xxxx.sd.mp4?s=xxxxxxxxxxxx&profile_id=xxx&oauth2_token_id=xxxxxxxx which seems and embedded player link to me (it works in a browser). What am I doing wrong? How do I get the link to play it in a native player?

**Comment by MrTheGood** [comment]
I recommend [ExoPlayer](https://github.com/google/ExoPlayer) to play the videos in.
