### ISSUE TITLE
Development branch as main branch

### ISSUE THREAD

**Issue by MrTheGood** [vimeo/vimeo-networking-java#323]
#### Issue Summary
The development branch is currently the main branch, meaning that the documentation most people will see is ahead of the current version. 

This causes problems like [this one](https://github.com/vimeo/vimeo-networking-java/issues/322) (I actually had the same problem when trying to get video files)

#### Expected Behavior
That the documentation shown in the README.md is the documentation of the current version of vimeo-networking-java

#### Actual Behavior
README.md shows documentation for a next version, which can cause headaches for users of the library.

**Comment by MrTheGood** [comment]
Another example where this causes problems can be found here #338

**Comment by anthonycr** [comment]
Version 2.0.0 is finally released and the documentation matches the latest version of the library, so closing this.
