### ISSUE TITLE
    implementation "com.vimeo.networking:vimeo-networking:1.1.3"

### ISSUE THREAD

**Issue by ishtiaqn2o** [vimeo/vimeo-networking-java#324]
I have tried to use this Library as a gradle dependency.. but its showing above issue.

But i have tried using 1.1.2 its sync successfully. I am trying to run the example project.. but 
 Configuration.Builder configBuilder =
                new Configuration.Builder(clientId, clientSecret, SCOPE, testAccountStore);

 here in last parameter it requires String parameter. I need help.. 

Thanks

**Comment by brendenozie** [comment]
Did You get an answer for this??

**Comment by divyashamar** [comment]
I am also facing the same issue .... and puzzled too much... not getting any useful content to make it work.
Please try to help me out soon..... Your prompt reply is awaited...

**Comment by AkshayGangurde** [comment]
Facing the same issue

**Comment by msya** [comment]
What do you mean by "but its showing above issue"? Version 1.1.3 hasn't been released yet. The latest version is 1.1.2.

**Comment by msya** [comment]
@AkshayGangurde @divyashamar @brendenozie @ishtiaqn2o  We are in the process of releasing version 1.1.3 this week. This will resolve the issue. In the meantime, please continue to use version 1.1.2 as it is the latest version of the SDK.

**Comment by msya** [comment]
Version 1.1.3 has been published to JCenter. You should be able to pull the library from it. Please us know if you come across any further issues.
