### ISSUE TITLE
Getting null from video.getPlay()

### ISSUE THREAD

**Issue by soonsam123** [vimeo/vimeo-networking-java#338]
I successfully get a Video instance from `fetchNetworkContent` but then I get null when invoking `video.getPlay()`.

```
String accessToken = getString(R.string.vimeo_access_token);
Configuration.Builder configBuilder = new Configuration.Builder(accessToken);
VimeoClient.initialize(configBuilder.build());

VimeoClient.getInstance().fetchNetworkContent(uri, new ModelCallback<Video>(Video.class) {
    @Override
    public void success(Video video) {
        // I successfully get here , but play is null.
        Play play = video.getPlay();
        if (play != null) {
            VideoFile hlsFile = play.getHlsVideoFile();
            String hlsLink = hlsFile.getLink();
            initializePlayer(Uri.parse(hlsLink));
        }
    }

    @Override
    public void failure(VimeoError error) {
        ...
    }
});
```

I am using a token which I created from [My Apps](https://developer.vimeo.com/apps) with my Vimeo Account.
I am expecting to get some result from `play` so I can get the hls link of the video.

I am following all the requesites the documentation ask to get video files.

1. User must be logged in. (I am using a valid token which I create in my app)
2. User must be the owner of the video. (I am the owner of the video I am asking for)
3. User must be PRO or higher (or the app must have the "can access owner's video files" capability). (My account is PRO, I can even get this link from vimeo playground)
4. Token must have the video_files scope. (My token has the video_files scope, actually I tried with all the scopes on but did not work)
5. User must be the owner of the API app making the request. (The app is mine that I created using the same account)

Trying for two days, how to solve this issue?

**Comment by MrTheGood** [comment]
That's because the development branch is the main branch for some reason. Because of that, the documentation is ahead of the actual API.

The correct way to currently get video links is found here: 
https://github.com/vimeo/vimeo-networking-java/blob/master/README.md#native-playback

**Comment by soonsam123** [comment]
It's true, I didn't notice that. Thank you!
`video.files` is deprecated but there is no problem in using it while waiting for future release?

```
Video video = ...; // obtain a video you own as described above
ArrayList<VideoFile> videoFiles = video.files;
if(videoFiles != null && !videoFiles.isEmpty()) {
     VideoFile videoFile = videoFiles.get(0); // you could sort these files by size, fps, width/height
     String link = videoFile.getLink();
     // load link
}
```

Now, the problem is that by using `videoFile.getLink()` I get the sd mp4 link. I am not finding a way to get the hls link.

**Comment by MrTheGood** [comment]
Yes, video.files will only be removed in a future update. I recommend fixing the API version to the current version (3.4 I think?) just so that the app doesn't suddenly break.

There is a way to get the hls link, but I don't remember how I did it. You'd have to look into the library  source code to find that.

**Comment by soonsam123** [comment]
Thank you for your attention. Actually, I am getting hls link like this.

```
ArrayList<VideoFile> videoFiles = video.files;
if (videoFiles != null && !videoFiles.isEmpty()) {
    VideoFile videoFile = videoFiles.get(videoFiles.size() - 1);
    String hlsLink = videoFile.getLink();
}
```

I tried it in more than 30 videos already and it is working. I am still not 100% sure but I think Hsl link is always **the last** in the array and **there is always** a hls link.

**Comment by msya** [comment]
Closing this issue. Please see https://github.com/vimeo/vimeo-networking-java/issues/368.
