### ISSUE TITLE
Library is not syncing in android studio

### ISSUE THREAD

**Issue by divyashamar** [vimeo/vimeo-networking-java#351]
I have tried to use this Library as a gradle dependency.. but its showing above issue.

But I have tried using 1.1.2 its sync successfully. I am trying to run the example project.. 
 I need help..

Thanks
DIVYA PRAKASH

**Comment by AkshayGangurde** [comment]
I'm facing the same issue with 1.1.3

**Comment by msya** [comment]
Version 1.1.3 hasn't been release yet. We are working on the releasing it soon. Version 1.1.2 is the latest version of the library.

**Comment by msya** [comment]
Closing this issue, because it is a duplicate of #324.
