### ISSUE TITLE
How to get HLS/DASH video file?

### ISSUE THREAD

**Issue by luizguilhermefr** [vimeo/vimeo-networking-java#364]
#### Issue Summary

Hi, I am a PRO user and I'd like to use HLS or DASH (adaptive strategy). However, at my `video.getDownload()`, only `mp4`files are available, and since the current version `1.x` doesn't support `getPlay()` yet, I cannot use `getDashVideoFile()` or similar.

#### Reproduction Steps

```java
VimeoClient.getInstance().fetchNetworkContent("/videos/" + videoId, new ModelCallback<Video>(Video.class) {
    @Override
    public void success(Video video) {
        ArrayList<VideoFile> videoFiles = video.getDownload();
        // this array doesn't have any HLS or DASH VideoFile
    }
}
```

Am I doing something wrong? Isn't every video intended to have this option?

**Comment by kvenn** [comment]
You should be able to achieve this by using the `files` on the `Video` object. The [`VideoFile`](https://github.com/vimeo/vimeo-networking-java/blob/v1.1.3-release/vimeo-networking/src/main/java/com/vimeo/networking/model/VideoFile.java#L67) will specify what type of file it is.

You can get more info on the README for 1.1.3: https://github.com/vimeo/vimeo-networking-java/tree/v1.1.3-release#native-playback

**Comment by kvenn** [comment]
The `getDownload()` method is for downloading specifically, so is correctly just sending back MP4 files.

DASH files not being returned is expected, but you should be seeing HLS within the `files` field on `Video`. I just checked with our API team and they've reassured me that all PRO users that can see MP4 files should also be able to see HLS. 

Can you just confirm for me real quick that none of the `VideoFile`s in the `files` array on `Video` don't have a `quality` of `VideoQuality.HLS`?

If you're still not seeing it, could you send me the request url you're using? Ideally with any headers you're sending along with it?

Thanks!

**Comment by luizguilhermefr** [comment]
Yes, using `files` instead of `getDownload()`, one more item is returned which is the HLS file :)

I found strange that the field is marked as deprecated, but I think it has something about the next release.

Thank you, Kyle.
