### ISSUE TITLE
What's is the current version?

### ISSUE THREAD

**Issue by soonsam123** [vimeo/vimeo-networking-java#368]
Sorry for the simple question, but last time I had a problem with versions.
What's the current version of the api? Which branch should I use now?

I was getting the Hls link using the code below:

```
ArrayList<VideoFile> videoFiles = video.files;
                if (videoFiles != null && !videoFiles.isEmpty()) {
                    // We are getting the last hlsLink, which is the HlsLink.
                    VideoFile videoFile = videoFiles.get(videoFiles.size() - 1);
                    String hlsLink = videoFile.getLink();
                    videoUri = Uri.parse(hlsLink);
                    initializePlayer(videoUri);
                }
```

`video.files` is deprecated, but in the other issue they told me I could still use it. Because it hasn't changed at. Should I keep getting the Hls link like that or can I update to the new way below?

```
Video video = ...; // obtain a video you own as described above
Play play = video.getPlay();
if (play != null) {
     VideoFile dashFile = play.getDashVideoFile();
     String dashLike = dashFile.getLink();
     // load link
     
     VideoFile hlsFile = play.getHlsVideoFile();
     String hlsLink = hlsFile.getLink();
     // load link
     
     ArrayList<VideoFile> progressiveFiles = play.getProgressiveVideoFiles();
     // pick a progressive file to play
}
```

**Comment by msya** [comment]
@soonsam123 If you are using version 1.1.3 of the SDK, the library uses API version 3.2. In this version, you could use the `files` field or the `play` field to get the HLS link. The files field is actually not deprecated in 3.2 even though it indicates it in the SDK. We will be updating it soon. If you want to use `files` field, you could get the HLS link by checking for the quality of the `VideoFile`.

For example:

```
List<VideoFile> videoFiles =  video.files
String hlsLink;

for (VideoFile videoFile : videoFiles) {
     if (videoFile.getQuality() == VideoQuality.HLS) {
            hlsLink = videoFile.getLink()
     }
}

```

Here is a person that had a similar issue. Please see https://github.com/vimeo/vimeo-networking-java/issues/364. If you may also the method that you have outline above.
