### ISSUE TITLE
How to cancel requests made with VimeoClient.getInstance().fetchNetworkContent()?

### ISSUE THREAD

**Issue by Cosminnv** [vimeo/vimeo-networking-java#409]
Hi, this is not an issues but more of a question and i didn't find anything in the documentation or searching on google. 
In my app the user can make numerous calls using "VimeoClient.getInstance().fetchNetworkContent()" and when the data is returned i start a Service. The problem is that sometimes the network is slow and the user makes a lot of requests, and sometimes i get a response when the user already closed the service, but the response starts another unwanted one. Is there anyway i can cancel all current calls or a way to "timeout" from the request? 

Thanks !

**Comment by anthonycr** [comment]
`VimeoClient.getInstance().fetchNetworkContent()` returns a `retrofit2.Call` object. This can be used to cancel the individual request by calling `Call.cancel()` on the object. 

If you wish to cancel all requests, then you will need to keep track of each `Call` in a data structure like a `List` and iteratively cancel each one.

**Comment by anthonycr** [comment]
Closing as there hasn't been any further action on this, and the new version of the library (2.0.0) supports cancellation of every request. Old library supported cancellation of most requests as well, but not the synchronous requests. Please open another issue if you have further questions.
