### ISSUE TITLE
always getting You must provide a valid authenticated access token.

### ISSUE THREAD

**Issue by omfg74** [vimeo/vimeo-networking-java#453]
I set up library as it said in manual here, but I get You must provide a valid authenticated access token. if I try to fetchNetworkContent and even if I call fetchCurrentUser. It seems im doing something wrong or I have wrong client_id and client_secret

**Comment by omfg74** [comment]
Has it any way to use access token and not to use Oauth

**Comment by omfg74** [comment]
Figured it out. The problem was in Dagger module, I do not know exactly why but it returned incorrect VimeoClient

**Comment by anthonycr** [comment]
Version 2.0.0 of the library is released and you can now use an access token instead of OAuth if you so choose. See the auth [README](https://github.com/vimeo/vimeo-networking-java/blob/develop/auth/README.md) for more info.
