### ISSUE TITLE
Play private videos

### ISSUE THREAD

**Issue by chetan-parekh19** [vimeo/vimeo-networking-java#496]
#### Issue Summary
How can we play private video in webview?

#### Reproduction Steps
I tried each link but always shows "Sorry! video can't accessible because it's private"

**Comment by anthonycr** [comment]
If the video privacy is `nobody`, then there is no way to watch the video without logging in as it's truly "private." If you want the video to be playable with a private link without the user needing to log in, then you can use the `unlisted` privacy (which I think is called "private link" in the UI). Let me know if that helps.
