### ISSUE TITLE
Why Would you remove the Java examples?? This is vimeo-networking-java

### ISSUE THREAD

**Issue by samgherman** [vimeo/vimeo-networking-java#504]
Why are all of the examples in Kotlin? The name of this is literally "vimeo-networking-java". I checked the history and it looks like the Java examples have been removed, the most recent ones were by @anthonycr. 

Does this not work for Java anymore? Are you going to rename this?

**Comment by anthonycr** [comment]
It works perfectly fine for Java, at Vimeo though we use Kotlin primarily (we have some Java code still) so the examples are now written in Kotlin. Let us know if you have any issues using the library in a Java project.
