### ISSUE TITLE
Files key from private videos

### ISSUE THREAD

**Issue by vrochamaia** [vimeo/vimeo-networking-java#72]
How can use this Api to get the 'files' key which hava a custom link to use in external players? The request is similar to this one: https://developer.vimeo.com/api/playground/videos

**Comment by kevinzetterstrom** [comment]
You can only access the 'files' key for your _own_ videos _if_ you are a PRO member. You do not have access to another user's video files.

**Comment by vrochamaia** [comment]
I'm a PRO member. I just want to show the videos from my account for the users.

**Comment by Dashron** [comment]
If you do not see the files key while making an API request to your own video files as a PRO user, please reach out to us at https://vimeo.com/help/contact and provide a link to the PRO user's account, and the last 5 characters of your access token.

**Comment by vrochamaia** [comment]
I can see this key using this link: https://developer.vimeo.com/api/playground/videos. I'm want to make this call using the Android Api( Vimeo - Networking ), but I'm not found any explation for how to do this.

**Comment by kevinzetterstrom** [comment]
There is an example of this in the [ReadMe](https://github.com/vimeo/vimeo-networking-java/blob/dev/README.md#sample-requests) and in the [example app](https://github.com/vimeo/vimeo-networking-java/tree/dev/example). You need to request a ```Video``` (or list of videos): each ```Video``` has a 'files' member.

**Comment by vrochamaia** [comment]
OK! Thank you for your response and sorry about my English!

**Comment by alfiehanssen** [comment]
No problem @vrochamaia thanks for filing the issue / asking the question 👍
