### ISSUE TITLE
Create example java application using vimeo-networking-java

### ISSUE THREAD

**Issue by kvenn** [vimeo/vimeo-networking-java#91]
#### Issue Summary

Currently only an Android example of the library exists. It'd be great to see a java project consume vimeo-networking-java. Feedback from [this SO post](http://stackoverflow.com/questions/37526958/vimeo-java-api-clickntap/37531078#comment62627414_37531078).

Additionally, it would be great to include an example of how to upload with this library.
#### Reproduction Steps

N/A
#### Expected Behavior

N/A
#### Actual Behavior

N/A

**Comment by Cortlandd** [comment]
Shouldn't this be closed now?

**Comment by kevinzetterstrom** [comment]
The current example application depends on Android. Once we create a pure Java example app we will close this.

**Comment by elronsmith** [comment]
When will be uploading video ?

**Comment by cabudies** [comment]
@kevinzetterstrom Can you please help me. I am new to Android and I wanna try vimeo api for viewing users only my private videos. I have implemented the code as per the documentation and given access token (generated from the web interface from developer.vimeo.com/apps). However, while trying to fetch content, it says you need authorisation. However, in the documentation it's mentioned that I can have access to private, public files using only access token. 

Please help me.
