### ISSUE TITLE
The library should be able to support the handling of multiple access tokens

### ISSUE THREAD

**Issue by kvenn** [vimeo/vimeo-networking-java#92]
#### Issue Summary

As of right now, vimeo-networking-java holds a singleton `VimeoClient` which can only hold one access token. In a single-user application this makes sense, but for a Java web server handling multiple users, a singleton won't work.
Find a way to allow for multiple access tokens in the context of a multi-user Java implementation.
#### Reproduction Steps

N/A
#### Expected Behavior

The VimeoClient singleton either isn't a singleton or houses support for managing multiple requests from multiple accesstokens.
#### Actual Behavior

You can only ever have one currently authenticated user at a time.

**Comment by anthonycr** [comment]
Latest version of the library supports this.
